# Generated by Django 5.0.2 on 2024-07-09 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_managers_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbqbooking',
            name='event_type',
            field=models.CharField(choices=[('private', 'Private BBQ'), ('company', 'Company BBQ'), ('wedding', 'Wedding BBQ'), ('school', 'School BBQ'), ('themed', 'Themed BBQ'), ('breakfast', 'Breakfast Catering'), ('holiday', 'Holiday Catering')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='bbqbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbq_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
